version: "3"
services:
  movie-server:
    image: siriling/movie-server:latest
    container_name: movie-server
    restart: unless-stopped
    # network_mode: bridge
    ports:
      - 8080:8080
    environment:
      -e API_URL='http://127.0.0.1:25500'
      -e SITE_NAME='订阅转换'
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: movie-redis
    restart: unless-stopped
    # network_mode: bridge
    volumes:
      - /root/appdata/redis/data:/dat